### ISSUE TITLE
Error: Root manifest not found

### ISSUE THREAD

**Issue by maximkrouk** [Didstopia/SwiftAction#4]
[Getting an error](https://github.com/MakeupStudio/swift-declarative-configuration/runs/1452550672?check_suite_focus=true) `root manifest not found`, config file is [here](https://github.com/MakeupStudio/swift-declarative-configuration/blob/main/.github/workflows/swift.yml), can you please help? 🙂 Also maybe it worth putting a bit more detailed usage example in README ^^

**Comment by maximkrouk** [comment]
@MaxDesiatov sorry for mentioning, but maybe u have an idea on how to fix it? 🌚

**Comment by MaxDesiatov** [comment]
You're running this action before `actions/checkout@v2`. Therefore, there is no code on the agent to build by the time `didstopia/SwiftAction@master` is running.

I'd also advise against the usage of `master`. The main benefit of this action is that you can select a Swift version to use, while Swift version on GitHub Actions runners may change without warning. I recommend that you select a version of this action in your workflow config to select a version of Swift that you're building with.

**Comment by maximkrouk** [comment]
Thank you, changing the order of the steps fixed the issue 🎉.
I tried `master` just to ensure, that the problem still exists in the latest sources. Now I use `v1.0.3` again 🙂
Maybe it worth mentioning that the order matters in README.md

**Comment by MaxDesiatov** [comment]
It could be added to `README.md`, but ordering of steps matters for any GitHub Action, not just this one. In GitHub Actions all steps are sequential, while jobs are parallel. You won't be able to successfully run any action that does something to your source code without checking out the source code first.

**Comment by maximkrouk** [comment]
True and obvious, but sometimes people stuck even on the easiest things. This mention could save me (and maybe someone else) some time 🙂.
At least here is an issue now, so I'll also leave a working example of complete `swift.yml` file
```yaml
name: swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: Didstopia/SwiftAction@v1.0.3
      with:
        swift-action: 'build -v --enable-test-discovery'
```
